development:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: um_pick_3_development
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: um_pick_3_test
  pool: 5
  timeout: 5000
